In [1]:
def is_prime(num):
    for i in range(2,num):
        if num%i==0:
            print("This is not a prime number")
            break
    else:
        print("This is a prime number")      
is_prime(10)          

This is not a prime number


# Iterator and Iterable objects

In [2]:
next("rishab")   #String by default is not an iterator

TypeError: 'str' object is not an iterator

In [ ]:
r = iter("rishab")  #A string is an iterable, hence we can convert any iterable to an iterator
print(type(r))

In [ ]:
next(r)  #Next function iterates to the next value

# Generator :
It generates new dataset everytime, but remembering the fact what dataset was generated the last time

In [ ]:
def gencube(n):
    for i in range(n):
        print(i**3)
        
gencube(5)

In [ ]:
def gencube(n):
    for i in range(n):
        yield i**3

gencube(5)

In [ ]:
for i in gencube(13):
    print(i, end=" ")

In [ ]:
next(gencube(13)) #this only returns 0 which means it is not an iterable

In [ ]:
i = iter(gencube(13))  #now generator is converted into iterator

In [ ]:
next(i)

In [ ]:
# create a fibonacci series but donot output any number, just create a generator function.

def genfi(n):
    a = 1
    b = 1
    for i in range(n):
        yield a
        a , b = b , a+b    

In [ ]:
v = iter(genfi(10))

In [ ]:
next(v)

In [ ]:
for i in genfi(20):
    print(i, end=" ")

# Map filter reduce

In [ ]:
#MAP :
#find the square of each number and return the list
# Approach 1
l = [2,3,4,5,6,7,8,9]
n = []
for i in l:
    n.append(i**2)
print(n, end=" ")

In [ ]:
#Approach 2 -Create a function to use MAP
def sq(n):
    return n**2

In [ ]:
list(map(sq,l))

In [ ]:
for i in map(sq,l):
    print(i, end=" ")

In [ ]:
#Approach 3 - Using lambda function

list(map(lambda x : x**2, l))

In [ ]:
# we can also store the lambda function insider a variable to increase the reusability
c = lambda x : x**2

In [ ]:
list(map(c,l))

In [ ]:
# Add the number of each list index wise
a = [1,2,3,4,5]
b = [5,6,7,4,3]
c = [6,7,8,6,5,5,4]

In [ ]:
def summation(x,y,z):
    return x+y+z

In [ ]:
list(map(summation, a,b,c))

In [ ]:
#Using lambda function

list(map(lambda x,y,z : x+y+z, a, b, c))

# AND NEURAL NETWORK

In [35]:
import pandas as pd
import numpy as np

In [36]:
AND = pd.DataFrame({"x1": (0,0,1,1), "x2": (0,1,0,1), "y": (0,0,0,1)})
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [37]:
#initializing random weights

w = np.random.randn(3) * 0.001
w

array([ 6.28808578e-04, -1.64162918e-03, -9.79964092e-06])

In [38]:
#Add activation function

a = lambda inputs , weight : np.where(np.dot(inputs, weight) > 0, 1 ,0)

Finally a training function that iterates the learning algorithm, returning the adapted weights

In [39]:
def train(inputs, targets, weights, eta, epochs):
    
    inputs = np.c_[inputs , -np.ones((len(inputs),1))]
    
    #As inputs + bias is ready, pass to the activation func
    for i in range(epochs):
        activations = a(inputs, weights)
        print(i , activations)
        
        weights = weights - eta * np.dot(np.transpose(inputs), activations - targets)
        print(i, weights)
        
    return weights

In [40]:
inputs = AND[["x1","x2"]]
targets = AND["y"]

In [41]:
train(inputs, targets, weights = w, eta = 0.01, epochs=12)

0 [1 0 1 0]
0 [0.00062881 0.00835837 0.0099902 ]
1 [0 0 0 0]
1 [ 1.06288086e-02  1.83583708e-02 -9.79964092e-06]
2 [1 1 1 1]
2 [0.00062881 0.00835837 0.0299902 ]
3 [0 0 0 0]
3 [0.01062881 0.01835837 0.0199902 ]
4 [0 0 0 1]
4 [0.01062881 0.01835837 0.0199902 ]
5 [0 0 0 1]
5 [0.01062881 0.01835837 0.0199902 ]
6 [0 0 0 1]
6 [0.01062881 0.01835837 0.0199902 ]
7 [0 0 0 1]
7 [0.01062881 0.01835837 0.0199902 ]
8 [0 0 0 1]
8 [0.01062881 0.01835837 0.0199902 ]
9 [0 0 0 1]
9 [0.01062881 0.01835837 0.0199902 ]
10 [0 0 0 1]
10 [0.01062881 0.01835837 0.0199902 ]
11 [0 0 0 1]
11 [0.01062881 0.01835837 0.0199902 ]


array([0.01062881, 0.01835837, 0.0199902 ])

# OR NEURAL NETWORK

In [74]:
OR = pd.DataFrame({"x1":(0,0,1,1), "x2":(0,1,0,1), "y": (0,1,1,1)})
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [75]:
#initialized the random weights
w = np.random.randn(3) * 0.003
w

array([-0.00032138, -0.00053896, -0.00073503])

In [76]:
#Add an activation function
a = lambda inputs, weights : np.where(np.dot(inputs, weights) > 0,1,0)

In [77]:
def train(inputs, targets, weights, eta, epochs):
    
    inputs = np.c_[inputs , -np.ones((len(inputs),1))]
    
    for i in range(epochs):
        activations = a(inputs, weights)
        print(i, activations)
        
        weights = weights - eta * np.dot(np.transpose(inputs), activations - targets)
        print(i, weights)
    
    return weights   

In [78]:
inputs = OR[["x1","x2"]]
targets = OR["y"]

In [79]:
train(inputs, targets, w, 0.0001, 30)

0 [1 1 1 0]
0 [-0.00022138 -0.00043896 -0.00073503]
1 [1 1 1 1]
1 [-0.00022138 -0.00043896 -0.00063503]
2 [1 1 1 0]
2 [-0.00012138 -0.00033896 -0.00063503]
3 [1 1 1 1]
3 [-0.00012138 -0.00033896 -0.00053503]
4 [1 1 1 1]
4 [-0.00012138 -0.00033896 -0.00043503]
5 [1 1 1 0]
5 [-2.13821742e-05 -2.38963322e-04 -4.35026308e-04]
6 [1 1 1 1]
6 [-2.13821742e-05 -2.38963322e-04 -3.35026308e-04]
7 [1 1 1 1]
7 [-2.13821742e-05 -2.38963322e-04 -2.35026308e-04]
8 [1 0 1 0]
8 [ 7.86178258e-05 -3.89633224e-05 -3.35026308e-04]
9 [1 1 1 1]
9 [ 7.86178258e-05 -3.89633224e-05 -2.35026308e-04]
10 [1 1 1 1]
10 [ 7.86178258e-05 -3.89633224e-05 -1.35026308e-04]
11 [1 1 1 1]
11 [ 7.86178258e-05 -3.89633224e-05 -3.50263084e-05]
12 [1 0 1 1]
12 [ 7.86178258e-05  6.10366776e-05 -3.50263084e-05]
13 [1 1 1 1]
13 [7.86178258e-05 6.10366776e-05 6.49736916e-05]
14 [0 0 1 1]
14 [ 7.86178258e-05  1.61036678e-04 -3.50263084e-05]
15 [1 1 1 1]
15 [7.86178258e-05 1.61036678e-04 6.49736916e-05]
16 [0 1 1 1]
16 [7.86178258e-0

array([7.86178258e-05, 1.61036678e-04, 6.49736916e-05])

# XOR GATE

In [119]:
XOR = pd.DataFrame({"x1":(0,0,1,1), "x2":(0,1,0,1), "y":(0,1,1,0)})
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [120]:
w = np.random.randn(3) * 0.003
w

array([ 0.00087786, -0.00192937,  0.00297855])

In [121]:
a = lambda inputs, weights : np.where(np.dot(inputs, weights)>0,1,0)

In [122]:
def train(inputs, targets, weights, eta, epochs):
    
    inputs = np.c_[inputs, -np.ones((len(inputs),1))]
    
    for i in range(epochs):
        activations = a(inputs, weights)
        print(i, activations)
        
        weights = weights - eta * np.dot(np.transpose(inputs), activations - targets)
        print(i, weights)
    
    return weights

In [123]:
inputs = XOR[["x1","x2"]]
targets = XOR["y"]

In [124]:
train(inputs, targets, w, 0.002, 50)

0 [0 0 0 0]
0 [ 2.87786351e-03  7.06292494e-05 -1.02145350e-03]
1 [1 1 1 1]
1 [ 0.00087786 -0.00192937  0.00297855]
2 [0 0 0 0]
2 [ 2.87786351e-03  7.06292494e-05 -1.02145350e-03]
3 [1 1 1 1]
3 [ 0.00087786 -0.00192937  0.00297855]
4 [0 0 0 0]
4 [ 2.87786351e-03  7.06292494e-05 -1.02145350e-03]
5 [1 1 1 1]
5 [ 0.00087786 -0.00192937  0.00297855]
6 [0 0 0 0]
6 [ 2.87786351e-03  7.06292494e-05 -1.02145350e-03]
7 [1 1 1 1]
7 [ 0.00087786 -0.00192937  0.00297855]
8 [0 0 0 0]
8 [ 2.87786351e-03  7.06292494e-05 -1.02145350e-03]
9 [1 1 1 1]
9 [ 0.00087786 -0.00192937  0.00297855]
10 [0 0 0 0]
10 [ 2.87786351e-03  7.06292494e-05 -1.02145350e-03]
11 [1 1 1 1]
11 [ 0.00087786 -0.00192937  0.00297855]
12 [0 0 0 0]
12 [ 2.87786351e-03  7.06292494e-05 -1.02145350e-03]
13 [1 1 1 1]
13 [ 0.00087786 -0.00192937  0.00297855]
14 [0 0 0 0]
14 [ 2.87786351e-03  7.06292494e-05 -1.02145350e-03]
15 [1 1 1 1]
15 [ 0.00087786 -0.00192937  0.00297855]
16 [0 0 0 0]
16 [ 2.87786351e-03  7.06292494e-05 -1.02145350

array([ 0.00087786, -0.00192937,  0.00297855])

In [10]:
for i in range(2000,3201):
    if (i%7==0) and (i%5 != 0): 
        print(i, end=", ")

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199, 

In [39]:
first = input("Enter first name: ")
last = input("Enter last name: ")
print("Output: ",first[::-1] +" "+ last[::-1])

Enter first name: rishab
Enter last name: raina
Output:  bahsir aniar


In [49]:
import math
# V = 4/3 * π * r^3
diameter = 12
r = diameter / 2
volume = 4/3 * math.pi * r**3
print(volume)

904.7786842338603
